// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dOSU__FfCiK2xsOTiyJ-TPcfbPjQrq0',
    appId: '1:994016422490:web:69ae3f23a61566c53ec663',
    messagingSenderId: '994016422490',
    projectId: 'restaurandes',
    authDomain: 'restaurandes.firebaseapp.com',
    storageBucket: 'restaurandes.firebasestorage.app',
    measurementId: 'G-BBW2BKEDBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLe_Dqc5iQX5ULfh4wBesoAmcq1VuadI',
    appId: '1:994016422490:android:b4de8525a10550f03ec663',
    messagingSenderId: '994016422490',
    projectId: 'restaurandes',
    storageBucket: 'restaurandes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRq3acj33ClfIMZUMNmiAYojQ6OLAUXE',
    appId: '1:994016422490:ios:292e605107bc1c8d3ec663',
    messagingSenderId: '994016422490',
    projectId: 'restaurandes',
    storageBucket: 'restaurandes.firebasestorage.app',
    iosBundleId: 'com.example.foodandesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBRq3acj33ClfIMZUMNmiAYojQ6OLAUXE',
    appId: '1:994016422490:ios:292e605107bc1c8d3ec663',
    messagingSenderId: '994016422490',
    projectId: 'restaurandes',
    storageBucket: 'restaurandes.firebasestorage.app',
    iosBundleId: 'com.example.foodandesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dOSU__FfCiK2xsOTiyJ-TPcfbPjQrq0',
    appId: '1:994016422490:web:c89549fbff2147453ec663',
    messagingSenderId: '994016422490',
    projectId: 'restaurandes',
    authDomain: 'restaurandes.firebaseapp.com',
    storageBucket: 'restaurandes.firebasestorage.app',
    measurementId: 'G-4Y650QS1LC',
  );
}
